In [2]:
import cv2
import os
import face_recognition as fr
import numpy as np


In [3]:
path='images'

In [4]:
mylist=os.listdir(path)
mylist

['messi.jpg', 'neymar.jpg', 'pedri.jpg', 'pogba.jpg', 'ronaldo.jpg']

In [5]:
imgs=[]
classnames=[]
for img in mylist:
    imgpath=os.path.join(path,img)
    print(imgpath)
    current_img=cv2.imread(imgpath)
    imgs.append(current_img)
    classnames.append(img.split(".")[0])
print(len(imgs))
print(classnames)


images\messi.jpg
images\neymar.jpg
images\pedri.jpg
images\pogba.jpg
images\ronaldo.jpg
5
['messi', 'neymar', 'pedri', 'pogba', 'ronaldo']


In [6]:
def faceencoding(images):
    encodedlist=[]
    for img in images:
        img1=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        face_in_frame=fr.face_locations(img1)
        encode=fr.face_encodings(img1,face_in_frame)[0]
        #print(face_in_frame)
        #print(encode)
        encodedlist.append(encode)
    return encodedlist

In [7]:
encoded_list_knownFaces=faceencoding(imgs)
encoded_list_knownFaces

[array([-0.16965024,  0.14365873,  0.03713674, -0.02495728, -0.11662358,
         0.10020726, -0.04542699, -0.04811674,  0.1280044 , -0.04963356,
         0.25728482,  0.00593487, -0.35403818, -0.00629526, -0.03596703,
         0.11941665, -0.14485757, -0.01671336, -0.1373509 , -0.19183043,
        -0.0278706 ,  0.13100114,  0.00387405,  0.024983  , -0.14121963,
        -0.2739518 ,  0.01217313, -0.17646323,  0.06395024, -0.14710514,
         0.00523447,  0.07309307, -0.08704846, -0.05104321,  0.04408039,
         0.0293804 ,  0.00335223, -0.08953694,  0.2153475 , -0.08742842,
        -0.0480739 , -0.00211797,  0.13012207,  0.26683649,  0.08138493,
         0.00431354,  0.04062252, -0.06629547,  0.1899883 , -0.21671727,
         0.09721327,  0.10747895,  0.12873429,  0.08963943,  0.06531955,
        -0.23868233, -0.020104  ,  0.17912194, -0.20671755,  0.11256728,
         0.0975024 ,  0.00063642, -0.10488285, -0.08914883,  0.22334416,
         0.1233324 , -0.16990268, -0.17108265,  0.0

In [ ]:
video=cv2.VideoCapture(0)
while True:
    suc,img=video.read()
    img1=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    face_in_frame=fr.face_locations(img1)
    # print(face_in_frame)
    encoded_faces=fr.face_encodings(img1,face_in_frame)
    # print(encoded_faces)
    for encfc,faceloc in zip(encoded_faces,face_in_frame):
        matches=fr.compare_faces(encoded_list_knownFaces,encfc)
        print(matches)
        facedistance=fr.face_distance(encoded_list_knownFaces,encfc)
        print(facedistance)
        matchind=np.argmin(facedistance)
        print(matchind)
        if matches[matchind]==True:
            name=classnames[matchind]
            print(name)
            y1,x2,y2,x1=faceloc
            cv2.rectangle(img,(x1, y1),(x2, y2),(0,255,0),2)
            cv2.putText(img,name,(x1, y1),cv2.FONT_HERSHEY_COMPLEX,1,(0,255,0),2)

    cv2.imshow("WEBCAM",img)
    if cv2.waitKey(1)&0XFF==ord('q'):
        break
video.release()
cv2.destroyAllWindows()

[True, False, False, False, False]
[0.58676244 0.7354056  0.74097944 0.90361409 0.77229354]
0
messi
[True, False, False, False, False]
[0.51655791 0.66671019 0.78336063 0.92563003 0.78641432]
0
messi
[False, False, False, False, False]
[0.62466684 0.68459255 0.68126665 0.81642256 0.67924722]
0
[False, False, False, False, False]
[0.85751013 0.66378501 0.72040905 0.62089155 0.71926504]
3
[True, False, False, False, False]
[0.54486709 0.70833254 0.80006511 0.95507116 0.83002916]
0
messi
[False, True, False, False, False]
[0.81926656 0.52732731 0.72542444 0.71451049 0.77812383]
1
neymar
[True, False, False, False, False]
[0.5132948  0.74320823 0.78068904 0.96126011 0.83656335]
0
messi
[False, True, False, False, False]
[0.82454636 0.45833049 0.71696754 0.77919829 0.75361011]
1
neymar
[True, False, False, False, False]
[0.4394362  0.70890858 0.7490039  0.9746819  0.76294924]
0
messi
[False, True, False, False, False]
[0.81823539 0.4074704  0.73085728 0.83653336 0.73402561]
1
neymar
[True, 